# Generated by Django 5.0.2 on 2024-12-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
