# Generated by Django 5.0.2 on 2025-01-10 19:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_organization_domain'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMatchBusinessCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(default='system', max_length=100)),
                ('updated_by', models.CharField(default='system', max_length=100)),
                ('business_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.businesscycle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
