# Generated by Django 5.0.2 on 2025-01-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_usermatchbusinesscycle'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermatchbusinesscycle',
            name='business_cycle',
        ),
        migrations.AddField(
            model_name='usermatchbusinesscycle',
            name='business_cycles',
            field=models.ManyToManyField(to='project.businesscycle'),
        ),
    ]
