# Generated by Django 5.0.2 on 2025-03-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_usermatchbusinesscycle_business_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_uid_outseta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
