# Generated by Django 5.0.2 on 2025-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_functionalareaembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrfp',
            name='status',
            field=models.CharField(blank=True, default='in-progress', max_length=100, null=True),
        ),
    ]
