# Generated by Django 5.0.2 on 2025-01-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_generatedrfp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedrfp',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedrfp',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
