# Generated by Django 5.0.2 on 2025-03-16 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_usermatchbusinesscycle_business_cycle_and_more'),
        ('project', '0004_generatedrfp_end_date_generatedrfp_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='custombusinesscycle',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
        migrations.AddField(
            model_name='customservice',
            name='organization_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.organization'),
        ),
    ]
